feat: [youtube-modal] index페이지 Youtube 관련 기능 추가
HakMukSa/GameWagon-Main-Front pull request #11
Opened 2023-05-29 12:52 UTC by chapsaldduk

1. Store에 youtube를 위한 저장소 추가, 그에 따른 타입 추가
2. Youtube thumbnail Slick 생성
3. Slick 에서 이미지 클릭 시 Modal이 열리면서 유튜브 iframe 출력
4. 디자인 아직 미반영

2023-05-29 15:47 UTC, dhtmdgkr123 requested changes
확인 부탁드립니다

2023-05-29 15:47 UTC, dhtmdgkr123 commented on app/components/index/Youtube.tsx
> +const settings = {
타입힌트 줄 수 있다면 추가 구다사이

2023-05-29 15:47 UTC, dhtmdgkr123 commented on app/components/index/Youtube.tsx
> +            ]}
배열로 리턴 되어야 하는 사유가 있을가용 ?? 궁금합니당 ~~

2023-05-29 15:47 UTC, dhtmdgkr123 commented on app/components/index/Youtube.tsx
> +        </div>
이부분 조금 더 다듬어서 컴포넌트화 했으면 하는데, 시간이 없다면 해당 부분은 case open하고 ignore해주심 될꺼 같습니당

2023-05-29 15:47 UTC, dhtmdgkr123 commented on app/main/store.ts
> +  youtube: [
```suggestion
  youtubeMetas: [
```
는 어떤가용 ?!

2023-05-29 18:33 UTC, chapsaldduk commented on app/components/index/Youtube.tsx
> +const settings = {
알겠습니다!

2023-05-29 18:34 UTC, chapsaldduk commented on app/components/index/Youtube.tsx
> +            ]}
여러개 함수가 동시에 실행되어야 해서 배열로 만들었습니다!

2023-05-29 18:36 UTC, chapsaldduk commented on app/components/index/Youtube.tsx
> +        </div>
이 Modal은 iframe만을 위한거라 이미지 등이 불가합니다. 추후에 필요하다면 컴포넌트화 할 것 같습니다!

2023-05-29 18:36 UTC, chapsaldduk commented on app/main/store.ts
> +  ],
추후에 고민해봐야 할 것 같습니다. 자동화를 하려면 고려해야 할 사항이 많을 것 같습니다!

2023-05-29 18:37 UTC, chapsaldduk commented on app/types/commons/store.ts
> +  youtube: YoutubeList[];
알겠습니다!

2023-05-29 18:39 UTC, chapsaldduk commented on app/types/commons/store.ts
> +};
코드에서 보이기 이쁘게 그냥 이렇게 만들었습니다! 수정하겠습니다!

2023-05-29 18:42 UTC, chapsaldduk commented on app/types/commons/store.ts
> +export type YoutubeList = {
알겠습니다!

2023-05-29 18:43 UTC, chapsaldduk commented on app/types/commons/store.ts
> +};
이것 역시 list를 props 타입을 선언하기 위해 만들었습니다!

2023-05-29 18:44 UTC, chapsaldduk commented on app/types/commons/store.ts
> +export type ImageList = {
코드상에서 next/Image와 겹쳐서 네이밍을 다르게 해봤습니다!

2023-05-29 18:44 UTC, chapsaldduk commented on app/main/store.ts
> +  youtube: [
알겠습니다!

2023-05-29 18:49 UTC, chapsaldduk commented
요청사항 일부 반영했습니다!
1. 네이밍 요청사항 반영
2. 타입힌트 추가
3. 미반영
    1. onClick 배열로 리턴
    2. Modal 컴포넌트화
    3. 타입 list로 한번 더 래핑 수정
    4. ImageList 타입 이름 변경
  https://github.com/HakMukSa/GameWagon-Main-Front/pull/11/commits/fb594972f0e3208131a9f134db95ce66f936dddc

2023-05-30 03:56 UTC, dhtmdgkr123 commented on app/components/index/Youtube.tsx
> +            ]}
동시에 실행되어야 한다는건 비순차적 동시성이 보장되어야 한다는건가요 ?
그렇다면 Promise 를 사용하는 방법도 있는데 저 스테이트 체인지에 굳이 동시성이 보장이 되어야 할 필요는 없을꺼 같아보입니당
저는 개인적으로 
```suggestion
            onClick={() => {
              setSelected(item.src);
              setSelectedTitle(item.title);
              setModalIsOpen(true);
            }}
```
와 같은 형태는 어떤지 의견이 궁금합니다 ~

2023-05-30 03:57 UTC, dhtmdgkr123 commented on app/main/store.ts
> +  ],
그러면 해당 부분은 API 안만드는걸로 하겟습니다, 그런데 API 추가에 대해서 확장 가능한 코드를 작성하는게 좋을꺼 같습니다

2023-05-30 03:58 UTC, dhtmdgkr123 commented on app/types/commons/store.ts
> +};
그러면 Youtube.tsx에서 받는 props의 형태가 제어된다면 해당 코드가 필요ㅕ없어질꺼 같아보이기도 합니다.

2023-05-30 03:58 UTC, dhtmdgkr123 commented on app/types/commons/store.ts
> +export type ImageList = {
그러면 next/Image 여기서 as 를 해보는거도 좋을꺼 같습니다 ~

2023-05-30 04:07 UTC, dhtmdgkr123 requested changes

2023-05-30 04:07 UTC, dhtmdgkr123 commented on app/types/commons/slick-settings.ts
내장 타입이 없다면 해당 부분은 불필요해 보입니당 ~

2023-05-30 04:07 UTC, dhtmdgkr123 commented on app/components/index/Youtube.tsx
> +export default function Youtube(props: Youtube) {
이 부분이 아예 YoutubeMeta[] 이렇게 받아버리면 Youtube 타입이 필요가 없어지는거져~~

2023-05-30 05:20 UTC, chapsaldduk commented on app/types/commons/slick-settings.ts
JS만 지원하는 라이브러리를 억지로 사용하다보니, 내장된 타입이 없습니다... 이대로 유지하겠습니다

2023-05-30 07:14 UTC, chapsaldduk commented
수정사항 반영 했습니다!
@dhtmdgkr123 
https://github.com/HakMukSa/GameWagon-Main-Front/pull/11/commits/a36926d4f1fd02e107f7099e227330b8b8ff8f8a

2023-05-30 08:23 UTC, chapsaldduk commented on app/components/index/Youtube.tsx
> +            ]}
알겠습니다!

2023-05-30 08:34 UTC, dhtmdgkr123 approved these changes
LGTM :)

2023-05-30 08:38 UTC, merged