style: [youtube-modal-design] youtube modal style 변경
HakMukSa/GameWagon-Main-Front pull request #12
Opened 2023-06-01 05:52 UTC by chapsaldduk

1. 닫기버튼 modal 오른쪽 위에서 modal content 오른쪽 위로 변경
2. modal content 왼쪽 위 이름 생성(추천 동영상)
3. modal content 영상 태그 생성
4. modal content 영상 위치 이동
5. modal content 영상 제목 스타일 변경
6. modal content 영상 아티스트(유튜버) 생성
7. store에 변경사항들 반영

2023-06-01 05:54 UTC, chapsaldduk commented
@dhtmdgkr123 
변경 후 이미지입니다
![image](https://github.com/HakMukSa/GameWagon-Main-Front/assets/77143594/0f49e525-0bb8-4c0f-8c6a-deb5c6872f28)

2023-06-01 06:03 UTC, dhtmdgkr123 requested changes

2023-06-01 06:03 UTC, dhtmdgkr123 commented on app/types/commons/slick-settings.ts
이거 불필요한거 아닌가용 ? ㄷㄷ

2023-06-01 06:03 UTC, dhtmdgkr123 commented on app/page.tsx
> +  const { images, youtubeMeta } = useStore();
사용안하는 데이터가 들어갔어용 !ㅠㅠ

2023-06-01 06:07 UTC, dhtmdgkr123 requested changes
suggestion 넣었습ㄴ다

2023-06-01 06:07 UTC, dhtmdgkr123 commented on app/page.tsx
> +  const { images, youtubeMeta } = useStore();
```suggestion
  const { images } = useStore();
```

사용안하는 데이터가 들어갔어용 !ㅠㅠ

2023-06-01 11:54 UTC, dhtmdgkr123 requested changes
tag쪽 리뷰 확인 부탁드립니다 ~

2023-06-01 11:54 UTC, dhtmdgkr123 commented on app/types/commons/store.ts
> +  tag: string;
태그는 여러개가 붙을 수 있으니 tags가 좋아보입니다

```suggestion
  tags: string[];
```

2023-06-01 11:54 UTC, dhtmdgkr123 commented on app/main/store.ts
> +      tag: "#추천게임동영상",
```suggestion
      tags: ["추천게임동영상", "게임", "리믹스"],
```

2023-06-01 11:54 UTC, dhtmdgkr123 commented on app/main/store.ts
> +      tag: "#추천게임동영상",
```suggestion
       tags: ["추천게임동영상", "게임", "리믹스", "블루 아카이브"],
```

2023-06-01 11:54 UTC, dhtmdgkr123 commented on app/components/index/Youtube.tsx
> +  const [selectedTag, setSelectedTag] = useState<string>("");
```suggestion
  const [selectedTags, setSelectedTag] = useState<string[]>([]);
```

2023-06-01 15:20 UTC, chapsaldduk commented
tag 배열로 변경 완료했습니다
https://github.com/HakMukSa/GameWagon-Main-Front/pull/12/commits/744c046fcc622fe40b93ce29fc321f5f0a66f122

2023-06-01 15:21 UTC, chapsaldduk commented on app/page.tsx
> +  const { images, youtubeMeta } = useStore();
깃 컨플릭트 나면서 생긴거 같습니다. 최신 버전엔 없을 예정입니다!

2023-06-01 15:21 UTC, chapsaldduk commented on app/types/commons/slick-settings.ts
깃 컨플릭트 나면서 생긴거 같습니다. 최신 버전엔 없을 예정입니다!

2023-06-01 19:15 UTC, chapsaldduk commented
@dhtmdgkr123 
빌드 에러 수정했습니다

2023-06-02 01:09 UTC, dhtmdgkr123 requested changes

2023-06-02 01:09 UTC, dhtmdgkr123 commented on app/components/index/Youtube.tsx
> +                  ))}
```suggestion
                  {selectedTags.map((tagValue: string, index: number): JSX.Element => (
                    <span key={index}>#{tagValue}&nbsp;</span>
                  ))}
```
는 어떤가 싶습니다

2023-06-02 01:09 UTC, dhtmdgkr123 commented on app/main/store.ts
> +      tags: ["#추천게임동영상", "#추천동영상"],
해시가 값에 반드시 붙어야 할까용 ? 태그 벨류만 들고있고 나머지는 좀 더 지유롭게 핸들링 할 수 있도록 하는건 어떨끼용 ?
```suggestion
      tags: ["추천게임동영상", "추천동영상"],
```

2023-06-02 01:09 UTC, dhtmdgkr123 commented on app/main/store.ts
> +      tags: ["#추천게임동영상"],
```suggestion
      tags: ["추천게임동영상"],
```
해시가 값에 반드시 붙어야 할까용 ? 태그 벨류만 들고있고 나머지는 좀 더 지유롭게 핸들링 할 수 있도록 하는건 어떨끼용 ?

2023-06-02 01:33 UTC, chapsaldduk commented on app/components/index/Youtube.tsx
> +                  ))}
알겠습니다!

2023-06-02 01:36 UTC, chapsaldduk commented on app/main/store.ts
> +      tags: ["#추천게임동영상", "#추천동영상"],
알겠습니다!

2023-06-02 01:36 UTC, chapsaldduk commented on app/main/store.ts
> +      tags: ["#추천게임동영상"],
알겠습니다!

2023-06-02 01:38 UTC, chapsaldduk commented
https://github.com/HakMukSa/GameWagon-Main-Front/pull/12/commits/77862a04ea49a9bbc3d2f06ed819e01dde33be63
수정사항 반영 완료했습니다!

2023-06-02 01:51 UTC, dhtmdgkr123 approved these changes
LGTM 💯

2023-06-02 01:55 UTC, merged