feat: [index-game-list] index 페이지 section03 게임리스트 추가
HakMukSa/GameWagon-Main-Front pull request #14
Opened 2023-06-27 11:08 UTC by chapsaldduk

1. 게임 리스트 get api추가
2. 해당 게임 리스트에 맞는 타입 추가
3. 인덱스 페이지에 게임 리스트 추가
4. 게임 이미지 컴포넌트 추가

2023-06-27 11:10 UTC, chapsaldduk commented
https://github.com/HakMukSa/GameWagon-Main-Front/pull/14/commits/1b7c7ce40c89615b73a483237e4a2f8ce5bd37e0
이번 코드에 대한 조언이 필요해서 오류가 남에도 불구하고 PR남깁니다.
게임 리스트 api를 받아오는 과정에서 null값을 허용해버림에 따라 많은 오류가 발생하는데, null값을 허용하지 않는 방법으로 데이터를 받아올 수 있을까요?
@handoo @dhtmdgkr123

2023-06-28 16:29 UTC, chapsaldduk commented
1. index 페이지에서 useState를 사용. zustand를 사용하지 않고 적용
2. gameRanking 섹션 컴포넌트 삭제
3. gameRanking 표시 스켈레톤 적용
https://github.com/HakMukSa/GameWagon-Main-Front/pull/14/commits/705030c4505e0406e0d16c104429ce721631149e

2023-06-30 18:46 UTC, chapsaldduk commented
1. 인덱스 페이지 section03 코드 리팩토링
2. 불필요한 console.log() 제거
3. 타입 정리
4. 불필요한 선언 제거
https://github.com/HakMukSa/GameWagon-Main-Front/pull/14/commits/dbcdbb2f102410daa716f5bed4b4caaef09c25a5

2023-07-01 02:15 UTC, chapsaldduk commented
1. 불필요한 코드 제거
https://github.com/HakMukSa/GameWagon-Main-Front/pull/14/commits/28d21c3f909126a1981342d046c45d1516e49c0e

2023-07-03 01:09 UTC, dhtmdgkr123 requested changes
화ㅣ긴화긴~~

2023-07-03 01:09 UTC, dhtmdgkr123 commented on app/page.tsx
> +} from "./components/commons/Games/GameImage";
요부분 @ 으로 하는 경로로 바뀌즈심 감사 ~

2023-07-03 01:09 UTC, dhtmdgkr123 commented on app/page.tsx
> +      const gameRanking10 = await gameList("steam", "MP");
steam 이부분 고정인가요 ? 지금부터 미리 다이나믹 하게 받아놓고, 스팀으로만 테스트 해보는거 추천해용 ~

2023-07-03 01:09 UTC, dhtmdgkr123 commented on app/types/commons/gamelist.ts
> +          language: "string";
```suggestion
          language: string;
```

2023-07-03 01:09 UTC, dhtmdgkr123 commented on app/types/commons/gamelist.ts
> +export type GameListRanking_Game = {
이부분이 위 리스트랑 ``` export type GameList  ``` 이랑 어떤게 다른건가용 ?!

2023-07-03 01:09 UTC, dhtmdgkr123 commented on app/types/commons/gamelist.ts
> +};
```suggestion
export type Game = {
    id: number;
    name: string;
    gameUrl: string;
    price: number;
    discountRate: number;
    releaseDate: string;
    ranking: string;
    platform: string;
    images: string[];
    extraData: {
      languages: [
        {
          language: "string";
          subtitle: boolean;
          dubbing: boolean;
          userPatch: boolean;
        }
      ];
      playTypes: {
        single: boolean;
        multi: boolean;
        online: boolean;
        vr: boolean;
      };
    };
};

export type GameRanking = {
    ranking: number;
    game: Game;
}

export type GameRankings = {
    rankings: GameRanking[];
};

```

이런느낌으로 타입이 분리되는건 어떤가여 ?

2023-07-03 01:09 UTC, dhtmdgkr123 commented on app/page.tsx
> +                  .map((game: GameListRanking_Game) => (
아래 타입이 변경되면 해당부분도 같이 변경 부탁드립니다 ~

2023-07-03 01:09 UTC, dhtmdgkr123 commented on app/page.tsx
> +                  .map((game: GameListRanking_Game) => (
아래 타입이 변경되면 해당부분도 같이 변경 부탁드립니다 ~

2023-07-03 03:26 UTC, chapsaldduk commented on app/api/game/game-list.tsx
> +    const errorMessages = error.response?.data.messages;
알겠습니다!

2023-07-03 03:57 UTC, chapsaldduk commented on app/components/index/GamesRanking.tsx
> +          />
해당 파일은 삭제하고 조언해주신 방법 사용해서 index 페이지로 전환했습니다!

2023-07-03 03:57 UTC, chapsaldduk commented on app/page.tsx
> +} from "./components/commons/Games/GameImage";
알겠습니다!

2023-07-03 03:58 UTC, chapsaldduk commented on app/page.tsx
> +      const gameRanking10 = await gameList("steam", "MP");
알겠습니다!

2023-07-03 03:59 UTC, chapsaldduk commented on app/types/commons/gamelist.ts
> +          language: "string";
죄송합니다 수정했습니다!

2023-07-03 04:01 UTC, chapsaldduk commented on app/types/commons/gamelist.ts
> +export type GameListRanking_Game = {
rankings의 포함 유무가 달라서 분리했는데, 아래 주신 리뷰로 진행하겠습니다!

2023-07-03 04:05 UTC, chapsaldduk commented on app/types/commons/gamelist.ts
> +};
그는...신이야...!

2023-07-03 04:06 UTC, chapsaldduk commented on app/page.tsx
> +                  .map((game: GameListRanking_Game) => (
알겠습니다!

2023-07-03 04:06 UTC, chapsaldduk commented on app/page.tsx
> +                  .map((game: GameListRanking_Game) => (
알겠습니다!

2023-07-03 04:10 UTC, dhtmdgkr123 requested changes

2023-07-03 04:10 UTC, dhtmdgkr123 commented on app/page.tsx
> +  const [games, setGames] = useState<GameRanking | {} | any>({});
Any 와 빈 객체를 안쓰는 방향으로 수정 구다사이

2023-07-03 04:17 UTC, chapsaldduk commented on app/page.tsx
> +  const [games, setGames] = useState<GameRanking | {} | any>({});
1. Game type 간결하게 변경
2. 경로 alias로 변경
3. 불필요한 코드 제거
https://github.com/HakMukSa/GameWagon-Main-Front/pull/14/commits/e708dbdf79376f8ebf30363192cbeeaa7f1df6bc

1. 타입 이름 미변경으로 인한 빌드 오류 수정
https://github.com/HakMukSa/GameWagon-Main-Front/pull/14/commits/e6cb785b4953ef12825fe50b7f9e1b14c5b17a38

수정 요청 중  index 페이지에서 game list api를 불러오는 부분은 다른 기능을 추가해서 다시 커밋하겠습니다!

2023-07-03 04:18 UTC, chapsaldduk commented
1. Game type 간결하게 변경
2. 경로 alias로 변경
3.불필요한 코드 제거
https://github.com/HakMukSa/GameWagon-Main-Front/commit/e708dbdf79376f8ebf30363192cbeeaa7f1df6bc

1.타입 이름 미변경으로 인한 빌드 오류 수정
https://github.com/HakMukSa/GameWagon-Main-Front/commit/e6cb785b4953ef12825fe50b7f9e1b14c5b17a38

수정 요청 중 index 페이지에서 game list api를 불러오는 부분은 다른 기능을 추가해서 다시 커밋하겠습니다!

2023-07-03 04:29 UTC, chapsaldduk commented
1. index 페이지 game list State 타입 수정
https://github.com/HakMukSa/GameWagon-Main-Front/pull/14/commits/ab022f55458c018b1335aa91db4f9b8f3e177a6d

2023-07-03 07:03 UTC, dhtmdgkr123 approved these changes
LGTM :)

2023-07-03 19:13 UTC, chapsaldduk commented
1. drop down menu를 추가해서 버튼으로 쉽게 api 재연동 가능 기능 추가
https://github.com/HakMukSa/GameWagon-Main-Front/pull/14/commits/83c3793a45486a85a333cace4339fb62b506749a

2023-07-04 03:52 UTC, chapsaldduk commented
1. sortBy 타입화해서 변경
https://github.com/HakMukSa/GameWagon-Main-Front/pull/14/commits/a09264af8bd2a8b705a0c5da2c9feff16aba54c7

2023-07-04 03:54 UTC, merged