feat: [games-game-list] games 페이지 구현
HakMukSa/GameWagon-Main-Front pull request #15
Opened 2023-07-04 19:36 UTC by chapsaldduk

구현 전 리팩토링

1. 파일 이름 & 함수 이름 변경
    1. game-list -> index-game-list 이름 변경
    2. 함수 이름 gameList -> gameList10 이름 변경
2. 새로운 api 연동 파일 생성
    1. games-game-list 생성(function gameList100)
    2. api 완성 시 주소 교체 Todo 작성
3. platform, sortBy를 store에 리스트화
    1. platformList, sortByList 타입 생성

2023-07-04 19:38 UTC, chapsaldduk commented
빌드 오류 수정
1. 수정한 부분에 key추가
https://github.com/HakMukSa/GameWagon-Main-Front/pull/15/commits/cbadc25ece74d70541dc4c6917446b71d75d8da7

2023-07-04 20:39 UTC, chapsaldduk commented
1. 불필요한 console.log()제거
2. games 페이지 일부 구현
    1. api 완성 시 나머지 구현을 위한 Todo 작성
https://github.com/HakMukSa/GameWagon-Main-Front/pull/15/commits/9d3e9c11e1b4c3d22f3a6500754a7852b753263e

2023-07-06 11:09 UTC, dhtmdgkr123 requested changes

2023-07-06 11:09 UTC, dhtmdgkr123 commented on app/page.tsx
> +              {sortByList.map((i: SortByList) => (
리턴타입도 명시 부탁드립니다 ~

2023-07-06 11:59 UTC, chapsaldduk commented on app/api/game/games-game-list.tsx
> +     */
100개 요청하는 api 완성됐나요? 스웨거를 봐도 안나와서 Todo로 작성했습니다

2023-07-06 11:59 UTC, chapsaldduk commented on app/games/page.tsx
> + */
알겠습니다!

2023-07-06 11:59 UTC, chapsaldduk commented on app/main/store.ts
> +    { value: "origin", name: "Origin" },
알겠습니다!

2023-07-06 11:59 UTC, chapsaldduk commented on app/page.tsx
> +              {sortByList.map((i: SortByList) => (
알겠습니다!

2023-07-09 06:17 UTC, chapsaldduk commented
1. Games game list api 반영
2. platform 타입 생성, 다른 코드들에 반영

https://github.com/HakMukSa/GameWagon-Main-Front/pull/15/commits/27a276548621d3f1053e017b27f2aba297dc9d2c

2023-07-09 07:03 UTC, chapsaldduk commented
1. 불필요한 console.log() 제거

https://github.com/HakMukSa/GameWagon-Main-Front/pull/15/commits/e47ead49ebbf4feccefe42ac2132f929e785c188

2023-07-09 07:04 UTC, dhtmdgkr123 requested changes

2023-07-09 07:04 UTC, dhtmdgkr123 commented on app/api/game/index-game-list.tsx
> +    console.log(data);
```suggestion
```

2023-07-09 07:04 UTC, chapsaldduk commented on app/api/game/index-game-list.tsx
> +    console.log(data);
한발 빨랐죠?

2023-07-09 07:04 UTC, dhtmdgkr123 approved these changes
coooooool

2023-07-09 07:05 UTC, merged