refactor: [project-rebuilding] 프로젝트 리뉴얼
HakMukSa/GameWagon-Main-Front pull request #16
Opened 2023-08-16 17:11 UTC by chapsaldduk

1. Chakra UI 추가
2. 프로젝트 구조 변경
    1. app으로 접근이 아닌 src/app으로 접근
    2. src/lib/pages에 퍼블리싱 생성
    3. src/app은 단순히 라우팅 역할만 하도록 변경
    4. login 페이지를 signin으로 이름 변경
    5. signin, signup 페이지는 auth/signin, auth/signup 경로로 변경

2023-08-23 14:56 UTC, chapsaldduk commented
1. youtube 기능 추가
2. 스타일은 나중에

https://github.com/HakMukSa/GameWagon-Main-Front/pull/16/commits/acc58ddba3eec238075109f87499cb1c9799a714

2023-09-16 16:50 UTC, chapsaldduk commented
1. JWT 스토어 생성
2. 로그인 시 JWT스토어에 JWT 토큰 값 저장

https://github.com/HakMukSa/GameWagon-Main-Front/pull/16/commits/04178d6bb2de3f14c85e3cf252d55585c462d0fd

2023-09-17 08:44 UTC, chapsaldduk commented
1. game information 페이지 생성
2. game information 스토어 생성
    1. game information 타입 파일 생성
3. 네이밍 이상한거 고침

https://github.com/HakMukSa/GameWagon-Main-Front/pull/16/commits/06dca6c44f38a7869c2bef0d1d87a15000824b5a

2023-09-17 08:52 UTC, chapsaldduk commented
1. 페이지 비어있어서 빌드 오류난거 수정
2. page config 변경

https://github.com/HakMukSa/GameWagon-Main-Front/pull/16/commits/525f7c61904a98ac22d013bcd6ccad57158499f1

2023-09-17 08:53 UTC, chapsaldduk commented
기존 프로젝트에서 pnpm + Next.JS 13 + Chakra UI + Tailwind css 로 이관 완료했습니다

2023-09-17 09:40 UTC, dhtmdgkr123 requested changes

2023-09-17 09:40 UTC, dhtmdgkr123 commented on public/404 Error-pana.svg
해당 이미지는 추 후 교체하는 방향으로 가겠습니다.

2023-09-17 09:40 UTC, dhtmdgkr123 commented on public/Launching-amico.svg
해당 이미지는 추 후 교체하는 방향으로 가겠습니다.

2023-09-17 09:40 UTC, dhtmdgkr123 commented on public/Under construction-amico.svg
해당 이미지는 추 후 교체하는 방향으로 가겠습니다.

2023-09-17 09:40 UTC, dhtmdgkr123 commented on public/chakra-ui-logomark-colored.svg
불필요 시 삭제 부탁드립니다.

2023-09-17 09:40 UTC, dhtmdgkr123 commented on public/next-app-chakra-ts.png
불필요 시 삭제 부탁드립니다.

2023-09-17 09:40 UTC, dhtmdgkr123 commented on public/nextjs-black-logo.svg
불필요 시 삭제 부탁드립니다.

2023-09-17 09:40 UTC, dhtmdgkr123 commented on public/nextjs-icon-dark.svg
불필요 시 삭제 부탁드립니다.

2023-09-17 09:40 UTC, dhtmdgkr123 commented on public/nextjs-icon-light.svg
불필요 시 삭제 부탁드립니다.

2023-09-17 09:40 UTC, dhtmdgkr123 commented on public/robots.txt
로봇 정책 호스트 변경, 사이트맵 변경 부탁드립니다.

2023-09-17 09:40 UTC, dhtmdgkr123 commented on public/sitemap-0.xml
로봇 정책 호스트 변경, 사이트맵 변경 부탁드립니다.

2023-09-17 09:40 UTC, dhtmdgkr123 commented on public/sitemap.xml
로봇 정책 호스트 변경, 사이트맵 변경 부탁드립니다.

2023-09-17 09:40 UTC, dhtmdgkr123 commented on public/ts-logo-512.svg
불필요 시 삭제 부탁드립니다.

2023-09-17 09:40 UTC, dhtmdgkr123 commented on public/vercel.svg
불필요 시 삭제 부탁드립니다.

2023-09-17 09:40 UTC, dhtmdgkr123 commented on renovate.json
이건 어떤 json인가용 ?

2023-09-17 09:40 UTC, dhtmdgkr123 commented on src/app/layout.tsx
> +const APP_NAME = "nextarter-chakra";
앱 네임 수정 부탁드립니다

2023-09-17 09:40 UTC, dhtmdgkr123 commented on src/app/layout.tsx
> +  description: "Next.js + chakra-ui + TypeScript template",
디스크립션 수정 부탁드립니다 ~

2023-09-17 09:40 UTC, dhtmdgkr123 commented on src/app/layout.tsx
> +  title: { default: APP_NAME, template: "%s | nextarter-chakra" },
타이틀 tempalte 부분 수정 부탁드립니다 ~

2023-09-17 09:40 UTC, dhtmdgkr123 commented on src/lib/components/Meta.tsx
> +const APP_NAME = "nextarter-chakra";
앱 네임 수정 부탁드립니다

2023-09-17 09:40 UTC, dhtmdgkr123 commented on src/lib/components/samples/CTASection.tsx
불필요 페이지 삭제 부탁드립니다.

2023-09-17 09:40 UTC, dhtmdgkr123 commented on src/lib/components/samples/SomeImage.tsx
불필요 페이지 삭제 부탁드립니다.

2023-09-17 09:40 UTC, dhtmdgkr123 commented on src/lib/components/samples/SomeText.tsx
불필요 페이지 삭제 부탁드립니다.

2023-09-17 09:41 UTC, chapsaldduk commented on next-sitemap.config.js
> +  siteUrl: "https://nextarter-chakra.sznm.dev",
https://github.com/HakMukSa/GameWagon-Main-Front/pull/16#issuecomment-1722428123
해당 PR에서 수정 완료했습니다

2023-09-17 09:41 UTC, chapsaldduk commented on public/404 Error-pana.svg
알겠습니다!

2023-09-17 09:41 UTC, chapsaldduk commented on public/Launching-amico.svg
알겠습니다!

2023-09-17 09:41 UTC, chapsaldduk commented on public/Under construction-amico.svg
알겠습니다!

2023-09-17 09:42 UTC, chapsaldduk commented on public/chakra-ui-logomark-colored.svg
알겠습니다!

2023-09-17 09:43 UTC, chapsaldduk commented on public/next-app-chakra-ts.png
알겠습니다!

2023-09-17 09:44 UTC, chapsaldduk commented on public/nextjs-black-logo.svg
알겠습니다!

2023-09-17 09:44 UTC, chapsaldduk commented on public/nextjs-icon-dark.svg
알겠습니다!

2023-09-17 09:44 UTC, chapsaldduk commented on public/nextjs-icon-light.svg
알겠습니다!

2023-09-17 09:46 UTC, chapsaldduk commented on public/sitemap.xml
알겠습니다!

2023-09-17 09:46 UTC, chapsaldduk commented on public/sitemap-0.xml
알겠습니다!

2023-09-17 09:46 UTC, chapsaldduk commented on public/robots.txt
알겠습니다!

2023-09-17 09:48 UTC, chapsaldduk commented on public/ts-logo-512.svg
알겠습니다!

2023-09-17 09:48 UTC, chapsaldduk commented on public/vercel.svg
알겠습니다!

2023-09-17 09:49 UTC, chapsaldduk commented on src/app/layout.tsx
> +const APP_NAME = "nextarter-chakra";
알겠습니다!

2023-09-17 09:50 UTC, chapsaldduk commented on src/app/layout.tsx
> +  description: "Next.js + chakra-ui + TypeScript template",
알겠습니다!

2023-09-17 09:50 UTC, chapsaldduk commented on src/app/layout.tsx
> +  title: { default: APP_NAME, template: "%s | nextarter-chakra" },
알겠습니다!

2023-09-17 09:50 UTC, chapsaldduk commented on src/lib/components/Meta.tsx
> +const APP_NAME = "nextarter-chakra";
알겠습니다!

2023-09-17 09:52 UTC, chapsaldduk commented on src/lib/components/samples/CTASection.tsx
알겠습니다!

2023-09-17 09:52 UTC, chapsaldduk commented on src/lib/components/samples/SomeImage.tsx
알겠습니다!

2023-09-17 09:52 UTC, chapsaldduk commented on src/lib/components/samples/SomeText.tsx
알겠습니다!

2023-09-17 10:08 UTC, chapsaldduk commented
1. 불필요한 파일들 제거
2. 프로젝트 사이트 이름, 설명 수정

https://github.com/HakMukSa/GameWagon-Main-Front/pull/16/commits/ce49a5f32bdc55075b7f0ce7cbd11f0125a99574

2023-09-17 14:05 UTC, dhtmdgkr123 approved these changes
LGTM :)

2023-09-18 03:46 UTC, merged