feat: [GAMEWAGON-#3] 수정사항 반영
HakMukSa/GameWagon-Main-Front pull request #4
Opened 2023-05-14 08:53 UTC by chapsaldduk

1. app/layout.tsx description 수정
2. community, database, game 등 page 타입 수정

Related with #3

2023-05-14 08:58 UTC, dhtmdgkr123 commented
@chapsaldduk 해당 PR은 #3에 이어지는 PR로 현재는 Base를 변경 했으나, 차 후 수정사항 반영 시 PR이 아닌 작업 브랜치에 이어서 커밋 부탁드립니다 ~

2023-05-14 09:00 UTC, dhtmdgkr123 requested changes

2023-05-14 16:49 UTC, chapsaldduk commented on app/layout.tsx
> +    // 추후에 SEO 고려, next/head 사용
네 좋습니다!

2023-05-15 00:36 UTC, dhtmdgkr123 approved these changes

2023-05-15 00:41 UTC, dhtmdgkr123 commented
approve 떠서 제가 merge 진행하도록 하겠습니다.

2023-05-15 00:42 UTC, merged