feat: [image slider] 메인페이지 이미지 슬라이더 구현
HakMukSa/GameWagon-Main-Front pull request #5
Opened 2023-05-15 00:20 UTC by chapsaldduk

1. 메인페이지 배너를 위한 이미지 슬라이더 구현
2. 예시 이미지는 반영하지 않음

2023-05-15 00:47 UTC, dhtmdgkr123 requested changes
변경사항 약간만 확인하면 될 꺼 같아요
그런데 다만 걱정되는건 해당 PR이 지금 다른 #3 PR하고 겹쳐서 컨플릭트가 날 수 있을꺼 같네용
#3 먼저 머지 진행하고 `feature/chapsaldduk/image-slider` 여기 브랜치 최신화 해서 push 해주세용 ~

2023-05-15 00:47 UTC, dhtmdgkr123 commented on app/components/Slick.tsx
> +const Slider = require("react-slick").default;
import 형태가 구 문법 import를 사용하고 있는것으로 보입니다, 해당 부분도 맞추어서 작업 부탁해요

2023-05-15 00:47 UTC, dhtmdgkr123 commented on app/components/Slick.tsx
> +];
이런 부분들은 dynamic 하게 갈꺼면 store로 관리하는건 어때영 ?

2023-05-15 00:47 UTC, dhtmdgkr123 commented on app/components/Slick.tsx
> +const settings = {
이부분에 타입힌트가 들어가면 더 편할 꺼 같아요

2023-05-15 07:42 UTC, chapsaldduk commented on app/components/Slick.tsx
> +const Slider = require("react-slick").default;
알겠습니다!

2023-05-15 07:42 UTC, chapsaldduk commented on app/components/Slick.tsx
> +];
반영하겠습니다!

2023-05-15 07:42 UTC, chapsaldduk commented on app/components/Slick.tsx
> +const settings = {
추가하겠습니다!

2023-05-15 07:43 UTC, chapsaldduk commented
요청주신 수정사항들 모두 반영 완료했습니다!
@dhtmdgkr123

2023-05-16 16:31 UTC, dhtmdgkr123 requested changes

2023-05-17 04:37 UTC, chapsaldduk commented on app/api/commons/types/image-list-setting.ts
> +export type ImageListSetting = {
수정하겠습니다!

2023-05-17 04:37 UTC, chapsaldduk commented on app/api/commons/types/image-list.ts
> +export type ImageList = {
수정하겠습니다!

2023-05-17 04:37 UTC, chapsaldduk commented on app/components/Slick.tsx
> +  console.log(images[0]);
수정하겠습니다!

2023-05-17 04:38 UTC, chapsaldduk commented on app/components/Slick.tsx
> +import useStore from "@/../store.js"; // image list
수정하겠습니다!

2023-05-17 04:38 UTC, chapsaldduk commented on app/nav.tsx
알겠습니다!
validation은 다른 branch로 찾아뵙겠습니다!

2023-05-17 04:38 UTC, chapsaldduk commented on app/page.tsx
추가하겠습니다!

2023-05-17 04:39 UTC, chapsaldduk commented on app/signup/page.tsx
다른 branch로 추가하겠습니다!

2023-05-17 04:39 UTC, chapsaldduk commented on app/page.tsx
> +import Slick from "@/components/Slick";
Slick은 컴포넌트라서 이대로 진행하려고 합니다!

2023-05-17 04:51 UTC, chapsaldduk commented
말씀하신 부분 전부 반영해서 커밋완료했습니다!
@dhtmdgkr123

2023-05-17 07:05 UTC, chapsaldduk commented
따로 말씀해주신 부분 전부 수정했습니다!
@dhtmdgkr123

2023-05-17 13:28 UTC, dhtmdgkr123 requested changes
Cheer up !!!

2023-05-17 13:28 UTC, dhtmdgkr123 commented on next.config.js
> +    remotePatterns: [
Todo로 CDN 생성시 도메인 추가 넣어주세요

2023-05-17 16:03 UTC, chapsaldduk commented on README.md
알겠습니다!

2023-05-17 16:09 UTC, chapsaldduk commented on app/login/page.tsx
> +      toast.error(`${errorMessages[errorKeys[0]]}`, {
Todo로 적어놓고 다음 브랜치에서 추가하겠습니다!

2023-05-17 16:10 UTC, chapsaldduk commented on app/login/page.tsx
>      } catch (error: any) {
네 알겠습니다!

2023-05-17 16:13 UTC, chapsaldduk commented on app/types/image-list.ts
> +export type imageList = {
불필요할거같다 하신 부분이라 파일을 삭제하겠습니다!

2023-05-17 16:13 UTC, chapsaldduk commented on app/types/image-list-setting.ts
> +export type imageListSetting = {
불필요할거같다 하신 부분이라 파일을 삭제하겠습니다!

2023-05-17 16:13 UTC, chapsaldduk commented on app/types/commons/async-event.ts
> +export type baseSyntheticEvent<E = object, C = any, T = any> = {
수정하겠습니다!

2023-05-17 16:13 UTC, chapsaldduk commented on app/main/store.ts
> +interface image {
수정하겠습니다!

2023-05-17 16:13 UTC, chapsaldduk commented on app/main/store.ts
> +interface images {
수정하겠습니다!

2023-05-17 16:14 UTC, chapsaldduk commented on app/main/store.ts
> +const useStore = create<images>((set) => ({
수정하겠습니다!

2023-05-17 16:15 UTC, chapsaldduk commented on .vscode/settings.json
알겠습니다!

2023-05-17 16:15 UTC, chapsaldduk commented on next.config.js
> +    remotePatterns: [
알겠습니다!

2023-05-17 16:24 UTC, chapsaldduk commented
Todo로 남겨둔 것들을 제외하고 수정 완료했습니다!
@dhtmdgkr123

2023-05-18 12:05 UTC, dhtmdgkr123 approved these changes
LGTM :)

2023-05-18 12:13 UTC, dhtmdgkr123 approved these changes

2023-05-18 12:18 UTC, merged